<?xml version= "1.0" ?>
<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Body dimensions -->
	<xacro:property name="body_link_x_dim" value="0.5"/>
	<xacro:property name="body_link_y_dim" value="0.3"/>
	<xacro:property name="body_link_z_dim" value="0.15"/>
	<!-- Wheel dimensions -->
	<xacro:property name="wheel_link_radius" value="0.075"/>
	<xacro:property name="wheel_link_length" value="0.05"/>
	<xacro:property name="wheel_link_lenght" value="0.05"/>
	<xacro:property name="wheel_link_z_location" value="-0.05"/>
	<!-- Material density -->
	<xacro:property name="body_density" value="2710.0"/>
	<xacro:property name="wheel_density" value="2710.0"/>
	<!-- Pi constant -->
	<xacro:property name="pi_const" value="3.14159265"/>
	<!-- Robot body and wheel mass -->
	<xacro:property name="body_mass" value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>
	<xacro:property name="wheel_mass" value="${wheel_density*pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length}"/>
	<!-- Moments of inertia of the wheel -->
	<xacro:property name="Iz_wheel" value="$(0.5*wheel_mass*wheel_link_radius*wheel_link_radius)" />
	<xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}" />
	<!-- This macro defines the complete inertial section of the wheel -->
	<!-- It is used later in the code -->
	<xacro:macro name="inertia_wheel">
		<inertial>
			<origin rpy="0 0 0" xz="0 0 0"/>
			<mass value="${wheel_mass}"/>
			<inertia 
            ixx="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}" 
            ixy="0.0" 
            ixz="0.0" 
            iyy="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}" 
            iyz="0" 
            izz="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}" />
		</inertial>
	</xacro:macro>
	<!-- over here we include the file that defines the extra gazebo options and motion cntrol driver -->
	<xacro:include filename="$(find robot_model_pkg)/urdf/robot.gazebo" />
	<!-- FROM HERE WE DEFINE LINKS, JOINTS -->
	<!-- we need this dummy link otherwise gazebo will complain -->
	<link name="dummy">
    </link>
	<joint name="dummy_joint" type="fixed">
		<parent link="dummy"/>
		<child link="body_link"/>
	</joint>
	<!-- START: BODY LINK OF THE ROBOT -->
	<link name="body_link">
		<visual>
			<geometry>
				<box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</visual>
		<collision>
			<geometry>
				<box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 0"/>
		</collision>
		<inertial>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<mass value="${body_mass}"/>
			<inertia
            ixx="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim + body_link_z_dim*body_link_z_dim)}" 
            ixy="0" 
            ixz="0" 
            iyy="${(1/12)*body_mass*(body_link_x_dim*body_link_x_dim + body_link_z_dim*body_link_z_dim)}" 
            iyz="0" 
            izz="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim + body_link_x_dim*body_link_x_dim)}"/>
		</inertial>
	</link>
	<!-- END:BODY OF THE LINK -->
	<!-- START: BACK RIGHT WHEEL OF THE ROBOT AND THE JOINT -->
	<joint name= "wheel1_joint" type="continuous" >
		<parent link="body_link"/>
		<child link="wheel1_link" />
		<origin xyz="-0.15 -0.175 -0.02" rpy="0 0 0" />
		<axis xyz="0 1 0"/>
		<limit effort="1000" velocity="1000"/>
		<dynamics damping="1.0" friction="1.0"/>
	</joint>
	<link name="wheel1_link">
		<visual>
			<origin rpy="1.570795 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="1.570795 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
			</geometry>
		</collision>
		<xacro:inertia_wheel />
	</link>
	<!-- END:BACK RIGHT WHEEL OF THE ROBOT AND THE JOINT-->
	<!-- START:BACK LEFT WHEEL OF THE ROBOT AND THE JOINT-->
	<joint name= "wheel2_joint" type="continuous" >
		<parent link="body_link"/>
		<child link="wheel2_link" />
		<origin xyz="-0.15 0.175 -0.02" rpy="0 0 0" />
		<axis xyz="0 1 0"/>
		<limit effort="1000" velocity="1000"/>
		<dynamics damping="1.0" friction="1.0"/>
	</joint>
	<link name="wheel2_link">
		<visual>
			<origin rpy="1.570795 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="1.570795 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
			</geometry>
		</collision>
		<xacro:inertia_wheel/>
	</link>
	<!-- END:BACK LEFT WHEEL OF THE ROBOT AND THE JOINT-->
	<!-- START:FRONT RIGHT WHEEL OF THE ROBOT AND THE JOINT-->
	<joint name= "wheel3_joint" type="continuous" >
		<parent link="body_link"/>
		<child link="wheel3_link" />
		<origin xyz="0.15 -0.175 -0.02" rpy="0 0 0" />
		<axis xyz="0 1 0"/>
		<limit effort="1000" velocity="1000"/>
		<dynamics damping="1.0" friction="1.0"/>
	</joint>
	<link name="wheel3_link">
		<visual>
			<origin rpy="1.570795 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="1.570795 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
			</geometry>
		</collision>
		<xacro:inertia_wheel/>
	</link>
	<!-- END:FRONT RIGHT WHEEL OF THE ROBOT AND THE JOINT-->
	<!-- START:FRONT LEFT WHEEL OF THE ROBOT AND THE JOINT-->
	<joint name= "wheel4_joint" type="continuous" >
		<parent link="body_link"/>
		<child link="wheel4_link" />
		<origin xyz="0.15 0.175 -0.02" rpy="0 0 0" />
		<axis xyz="0 1 0"/>
		<limit effort="1000" velocity="1000"/>
		<dynamics damping="1.0" friction="1.0"/>
	</joint>
	<link name="wheel4_link">
		<visual>
			<origin rpy="1.570795 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
			</geometry>
		</visual>
		<collision>
			<origin rpy="1.570795 0 0" xyz="0 0 0"/>
			<geometry>
				<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
			</geometry>
		</collision>
		<xacro:inertia_wheel/>
	</link>
	<!-- END: FRONT LEFT WHEEL OF THE ROBOT AND THE JOINT-->
</robot>

